# Lista de nombres completos prohibidos que deben coincidir exactamente para ser excluidos.
nombres_prohibidos = [
    "alexandra acosta",
    "andres arango zapata",
    "angela maria martinez restrepo",
    "asley crisell caicedo mateus",
    "carlos eduardo franco munoz",
    "carlos marino escobar vazques",
    "carolina munoz diez",
    "claudia paola rojas",
    "claudia milena londono",
    "diana carolina gomez aguirre",
    "diego fernando briceno nieto",
    "herney borreo hincapie",
    "jairo hernando vargas camacho",
    "javier andres correo quiceno",
    "javier ignacio cormane fandino",
    "katherine garzon patino",
    "maria cristina casas piedrahita",
    "maria teresa garcia riofrio",
    "monica cuervo jimenez",
    "monica suarez gutierrez",
    "natalia elizabeth ruiz cerquera",
    "neicy restrepo hernandez",
    "sandra milena medina martinez",
    "sandra rivillas",
    "sergio andres manjarres maestre",
    "victor hugo arturo",
    "victoria duque",
    "victoria eugenia alzate martinez",
    "indira yasmin ocando brito",
]